# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: fix-encoding-pragma
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        args: ["--format", "pylint"]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a1
    hooks:
      - id: pylint
        entry: python -m pylint.__main__
        language: system
default_language_version:
  python: python3
